---
title: "Biopsy_Deseq"
author: "sudarshan.shetty@wur.nl"
date: "`r Sys.Date()`"
output:
  rmdformats::html_clean:
    highlight: kate
---

## Libraries  

```{r setup, include=FALSE}

library(ggplot2)
library(microbiome)
library(dplyr)
library(phyloseq)
library(RColorBrewer)
library(DESeq2)
library(ggpubr)

my_theme <- theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.text.y = element_text(face="italic"))
getwd()

set.seed(85854482)

```


## Biopsy  

## FDR vs DC

```{r}

ps.bxa <- readRDS(file="../phyloseqobjects/ps.bx.rds")
meta(ps.bxa)

ps.bx1.fdr.dc.0 = subset_samples(ps.bxa, Diagnosis != "CeD")

ps.bx1.fdr.dc.0 = subset_taxa(ps.bx1.fdr.dc.0, !is.na(Family))

ps.bx1.fdr.dc <-filter_taxa(ps.bx1.fdr.dc.0, function(x) sum(x > 10) > (0.10*length(x)), TRUE)
ps.bx1.fdr.dc

meta.bx <- meta(ps.bx1.fdr.dc)
diagdds_bx.fdr.dc = phyloseq_to_deseq2(ps.bx1.fdr.dc, ~ Diagnosis)
dds_bx.fdr.dc = DESeq(diagdds_bx.fdr.dc, test="Wald", fitType="local")
```


```{r}

otu.ab1 <- abundances(ps.bx1.fdr.dc)

res = results(dds_bx.fdr.dc, cooksCutoff = FALSE)
res_tax = cbind(as.data.frame(res), as.matrix(rownames(otu.ab1)), OTU = rownames(res))

res_tax = cbind(as(res_tax, "data.frame"), as(tax_table(ps.bx1.fdr.dc)[rownames(res_tax), ], "matrix"))

res_tax_sig = subset(res_tax, padj < 0.01 & 0 < abs(log2FoldChange))
res_tax$Significant <- ifelse(rownames(res_tax) %in% rownames(res_tax_sig) , "Yes", "No")
res_tax$Significant[is.na(res_tax$Significant)] <- "No"
  
sig_res <- res_tax[rownames(res_tax_sig),"OTU"]
res_table <- data.frame(res_tax_sig$baseMean , res_tax_sig$log2FoldChange,res_tax_sig$padj)
row.names(res_table)<- rownames(res_tax_sig)
data_to_write<-res_tax_sig[,c("baseMean","log2FoldChange","pvalue","padj","Phylum", "Class", "Order", "Family", "Genus")]
data_to_write$DifferentaillyAbundant<-levels(meta.bx[,"Diagnosis"])[as.numeric(data_to_write$log2FoldChange>0)+1]
data_to_write[is.na(data_to_write <- data_to_write)] <- "g__"

# Total numer of OTUs DA

nrow(data_to_write)


# No. of genera DA
length(unique(data_to_write$Genus))

# Which genera
unique(data_to_write["Genus"])

write.csv(data_to_write,paste("biopsyNB_significant_",paste(levels(meta.bx$Diagnosis),collapse="_vs_"),".csv",sep=""))
head(data_to_write)

df1 <- mutate(data_to_write, Genus, Genus= paste(Family, "-",data_to_write$Genus ))
length(unique(df1$Family))

df1$Genus <- gsub('f__', '', df1$Genus)
df1$Genus <- gsub('g__', '', df1$Genus)



fdr.dc.bx <- ggplot(df1, aes(log2FoldChange, Genus)) + geom_point(aes(color = DifferentaillyAbundant), shape = 21, size = 3) + scale_color_manual(values= c("#fdae61", "#8da0cb")) + theme(axis.text.y = element_text(face="italic")) + my_theme + geom_vline(xintercept = 0)
fdr.dc.bx 

ggsave("../Figures/additional/Deseq_bx_DC_FDR_bx.pdf", height = 6, width = 8)

#"#d7191c", "#fdae61", "#8da0cb
```

## FDR CeD

```{r}
ps.bx1.fdr.ced.0 = subset_samples(ps.bxa, Diagnosis != "DC")

ps.bx1.fdr.ced.0 = subset_taxa(ps.bx1.fdr.ced.0, !is.na(Family))

ps.bx1.fdr.ced <-filter_taxa(ps.bx1.fdr.ced.0, function(x) sum(x > 10) > (0.10*length(x)), TRUE)
ps.bx1.fdr.ced

meta.bx <- meta(ps.bx1.fdr.ced)
diagdds_bx.fdr.ced = phyloseq_to_deseq2(ps.bx1.fdr.ced, ~ Diagnosis)
dds_bx.fdr.ced = DESeq(diagdds_bx.fdr.ced, test="Wald", fitType="local")
```


```{r}

otu.ab1 <- abundances(ps.bx1.fdr.ced)

res = results(dds_bx.fdr.ced, cooksCutoff = FALSE)
res_tax = cbind(as.data.frame(res), as.matrix(rownames(otu.ab1)), OTU = rownames(res))

res_tax = cbind(as(res_tax, "data.frame"), as(tax_table(ps.bx1.fdr.ced)[rownames(res_tax), ], "matrix"))

res_tax_sig = subset(res_tax, padj < 0.01 & 0 < abs(log2FoldChange))
res_tax$Significant <- ifelse(rownames(res_tax) %in% rownames(res_tax_sig) , "Yes", "No")
res_tax$Significant[is.na(res_tax$Significant)] <- "No"
  
sig_res <- res_tax[rownames(res_tax_sig),"OTU"]
res_table <- data.frame(res_tax_sig$baseMean , res_tax_sig$log2FoldChange,res_tax_sig$padj)
row.names(res_table)<- rownames(res_tax_sig)
data_to_write<-res_tax_sig[,c("baseMean","log2FoldChange","pvalue","padj","Phylum", "Class", "Order", "Family", "Genus")]
data_to_write$DifferentaillyAbundant<-levels(meta.bx[,"Diagnosis"])[as.numeric(data_to_write$log2FoldChange>0)+1]
data_to_write[is.na(data_to_write <- data_to_write)] <- "g__"


# Total numer of OTUs DA

nrow(data_to_write)


# No. of genera DA
length(unique(data_to_write$Genus))

# Which genera
unique(data_to_write["Genus"])


write.csv(data_to_write,paste("biopsyNB_significant_",paste(levels(meta.bx$Diagnosis),collapse="_vs_"),".csv",sep=""))
head(data_to_write)


df2 <- mutate(data_to_write, Genus, Genus= paste(Family, "-",data_to_write$Genus ))

df2$Genus <- gsub('f__', '', df2$Genus)
df2$Genus <- gsub('g__', '', df2$Genus)


fdr.ced.bx <- ggplot(df2, aes(log2FoldChange, Genus)) + geom_point(aes(color = DifferentaillyAbundant), shape = 21, size = 3) + scale_color_manual(values= c("#d7191c", "#8da0cb")) + theme(axis.text.y = element_text(face="italic")) + my_theme + geom_vline(xintercept = 0)
fdr.ced.bx 
ggsave("../Figures/additional/Deseq_bx_CeD_FDR_bx.pdf", height = 6, width = 8)

#"#d7191c", "#fdae61", "#8da0cb
```



## CeD DC

```{r}
ps.bx1.dc.ced.0 = subset_samples(ps.bxa, Diagnosis != "FDR")

ps.bx1.dc.ced.0 = subset_taxa(ps.bx1.dc.ced.0, !is.na(Family))

ps.bx1.dc.ced <-filter_taxa(ps.bx1.dc.ced.0, function(x) sum(x > 10) > (0.10*length(x)), TRUE)
ps.bx1.dc.ced

meta.bx <- meta(ps.bx1.dc.ced)
diagdds_dc.ced = phyloseq_to_deseq2(ps.bx1.dc.ced, ~ Diagnosis)
dds_dc.ced = DESeq(diagdds_dc.ced, test="Wald", fitType="local")
```


```{r}

otu.ab1 <- abundances(ps.bx1.dc.ced)

res = results(dds_dc.ced, cooksCutoff = FALSE)
res_tax = cbind(as.data.frame(res), as.matrix(rownames(otu.ab1)), OTU = rownames(res))

res_tax = cbind(as(res_tax, "data.frame"), as(tax_table(ps.bx1.dc.ced)[rownames(res_tax), ], "matrix"))

res_tax_sig = subset(res_tax, padj < 0.01 & 0 < abs(log2FoldChange))
res_tax$Significant <- ifelse(rownames(res_tax) %in% rownames(res_tax_sig) , "Yes", "No")
res_tax$Significant[is.na(res_tax$Significant)] <- "No"
  
sig_res <- res_tax[rownames(res_tax_sig),"OTU"]
res_table <- data.frame(res_tax_sig$baseMean , res_tax_sig$log2FoldChange,res_tax_sig$padj)
row.names(res_table)<- rownames(res_tax_sig)
data_to_write<-res_tax_sig[,c("baseMean","log2FoldChange","pvalue","padj","Phylum", "Class", "Order", "Family", "Genus")]
data_to_write$DifferentaillyAbundant<-levels(meta.bx[,"Diagnosis"])[as.numeric(data_to_write$log2FoldChange>0)+1]

data_to_write[is.na(data_to_write <- data_to_write)] <- "g__"

# Total numer of OTUs DA

nrow(data_to_write)


# No. of genera DA
length(unique(data_to_write$Genus))

# Which genera
unique(data_to_write["Genus"])


write.csv(data_to_write,paste("biopsyNB_significant_",paste(levels(meta.bx$Diagnosis),collapse="_vs_"),".csv",sep=""))
head(data_to_write)




df3 <- mutate(data_to_write, Genus, Genus= paste(Family, "-",data_to_write$Genus ))

df3$Genus <- gsub('f__', '', df3$Genus)
df3$Genus <- gsub('g__', '', df3$Genus)


dc.ced.bx <- ggplot(df3, aes(log2FoldChange, Genus)) + geom_point(aes(color = DifferentaillyAbundant), shape = 21, size = 3) + scale_color_manual(values= c("#d7191c", "#fdae61")) + theme(axis.text.y = element_text(face="italic")) + my_theme + geom_vline(xintercept = 0)
dc.ced.bx 
ggsave("../Figures/additional/Deseq_bx_CeD_DC_bx.pdf", height = 6, width = 8)
#"#d7191c", "#fdae61", "#8da0cb


```



```{r}

deseq.bx <- ggarrange(fdr.dc.bx, dc.ced.bx, fdr.ced.bx, ncol = 3, labels = c("a", "b", "c"), legend = "right")
ggsave("../Figures/Fig4a_b_c_eseq_bx.pdf", height = 6, width = 20)

sessionInfo()
```





